config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get '/help', to:'static_pages#help'
  get '/about', to:'static_pages#about'
  get '/contact', to:'static_pages#contact'

  # resourcesを使用することで、usersに関して名前付きrootが利用可能になる
  resources :users
  get '/signup', to:'users#new'
  post '/signup', to:'users#create'

  # sessionリソースに対するルーティング
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete '/logout', to:'sessions#destroy'

  # 11.1.1 AccountActivationsの名前付きルート
  # GET /account_activation/<token>/edit edit edit_account_activation_url(token)
  resources :account_activations, only: [:edit]

  # 12.1.1 PasswordResetsの名前付きルート
  # GET	  /password_resets/new	        new	   new_password_reset_path
  # POST	/password_resets	            create password_resets_path
  # GET	  /password_resets/<token>/edit	edit	 edit_password_reset_url(token)
  # PATCH /password_resets/<token>	    update password_reset_url(token)
  resources :password_resets, only: [:new, :create, :edit, :update]

  # 13.3 Micropostの名前付きルート
  # POST   /microposts   create  microposts_path
  # DELETE /microposts/1 destroy micropost_path(micropost)
  resources :microposts, only: [:create, :destroy]

  # 14.2.2 followingアクションとfollowersアクションを追加
  # GET	/users/1/following	following	following_user_path(1)
  # GET	/users/1/followers	followers	followers_user_path(1)
  resources :users do
    member do
      # memberメソッドを使用するとidを含むURLを作成する
      get :following, :followers
    end
  end

  # 14.2.2 Relationshipの名前付きルート
  resources :relationships, only: [:create, :destroy]


end

app/controllers/password_resets_controller.rb
# 12.1.1
class PasswordResetsController < ApplicationController
  before_action :get_user, only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_exiration, only: [:edit, :update]

  # 12.1.1
  def new
  end

  # 12.1.3
  def create
    # 12.1.3
    @user = User.find_by( email: params[:password_reset][:email].downcase )
    #
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "パスワード再設定用のメールを送信しました！"
      redirect_to root_url
    else
      flash[:danger] = "入力したメールアドレスが見つかりません。"
      # 12.1.2 renderにしないと情報が残ってしまう？
      render "new"
    end
  end

  # 12.1.1
  def edit
  end

  # 12.3.2
  def update
    if params[:user][:password].empty?
      # 12.3.2 エラーメッセージ(erros)にパスワード(:password)がブランク(:blank)だった時のデフォルトメッセージを格納
      @user.errors.add(:password, :blank)
      render "edit"
    elsif @user.update_attributes(user_params)
      log_in @user
      # 12.3.3 演習；パスワード再設定に成功したら再設定ダイジェストを削除する
      @user.update_attribute(:reset_digest, nil)
      flash[:success] = "パスワードの再設定に成功しました！"
      redirect_to @user
    else
      render "edit"
    end
  end


  private

  # 12.3.1 ユーザー取得用メソッド
  def get_user
    @user = User.find_by(email: params[:email])
  end

  # 12.3.1 ユーザーが正しいかを精査
  def valid_user
    unless ( @user && @user.activated? &&
            @user.authenticated?(:reset, params[:id]) )
      redirect_to root_url
    end
  end

  # 12.3.2 パスワード再設定期限が切れていないか確認する
  def check_exiration
    if @user.password_reset_expired?
      message = "expired!パスワード再設定の有効期限が切れています！再度再設定登録を行ってください。"
      flash[:danger] = message
      redirect_to new_password_reset_url
    end
  end

  # 12.3.2 パスワード、確認パスワードのみをアクセス許可にする
  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end



end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<!-- 12.3.1 -->
<% provide(:title, 'Reset password') %>
<h1>Reset password</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      <!-- 13.3.2 objectを使用するように修正 -->
      <%= render 'shared/error_messages', object: f.object %>

      <!-- 12.3.1 updateでもメールアドレスを使用するため、hidden項目として画面に保持する -->
      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "Update password", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<!-- 12.1.2 -->
<% provide(:title, 'Forget password') %>
<h1>Forget password</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>